image_speed = 0
image_index = 0
c_button = make_colour_rgb(25, 42, 67)
text = "Publicar"
effect_hover = 0
anim = 0
posy = 2
rot = 0
etiqueta1 = ""
etiqueta2 = ""
url = ""
user_temp = obj_gb_level.user
press = 1
verify = 0
word[0] = "puta"
word[1] = "puto"
word[2] = "chupa"
word[3] = "pta"
word[4] = "perra"
word[5] = "zorra"
word[6] = "sorra"
word[7] = "cp"
word[8] = "cocaina"
word[9] = "cocaína"
word[10] = "droga"
word[11] = "droga"
word[12] = "pene"
word[13] = "pne"
word[14] = "nepe"
word[15] = "verga"
word[16] = "vrga"
word[17] = "porquería"
word[18] = "porqueria"
word[19] = "mierda"
word[20] = "gay"
word[21] = "gey"


