var nn_text;
draw_self()
draw_set_font(global.font_google)
draw_set_color(c_black)
nn_text = scr_add3points(global.levelguardabot, 270, 52)
draw_text((camera_get_view_x(view_get_camera(0)) + 52), (camera_get_view_y(view_get_camera(0)) + 54), string_hash_to_newline(nn_text))
draw_set_color(c_etiquetas)
draw_text((camera_get_view_x(view_get_camera(0)) + 59), (camera_get_view_y(view_get_camera(0)) + 74), string_hash_to_newline(user))
draw_text((camera_get_view_x(view_get_camera(0)) + 195), (camera_get_view_y(view_get_camera(0)) + 111), string_hash_to_newline(text[global.etiqueta1_temp]))
draw_text((camera_get_view_x(view_get_camera(0)) + 195), (camera_get_view_y(view_get_camera(0)) + 123), string_hash_to_newline(text[global.etiqueta2_temp]))
draw_sprite(spr_stamps, index_stamp, (camera_get_view_x(view_get_camera(0)) + 44), (camera_get_view_y(view_get_camera(0)) + 89))
if (global.condiciones == 0)
    draw_text((camera_get_view_x(view_get_camera(0)) + 195), (camera_get_view_y(view_get_camera(0)) + 91), string_hash_to_newline(text[15]))
else
    draw_sprite(spr_cond_hud, global.condiciones_count, (camera_get_view_x(view_get_camera(0)) + 195), (camera_get_view_y(view_get_camera(0)) + 91))
draw_sprite(spr_carteles, global.apariencia, (camera_get_view_x(view_get_camera(0)) + 300), (camera_get_view_y(view_get_camera(0)) + 93))
draw_sprite(spr_cards_entorno, entorno_image, (camera_get_view_x(view_get_camera(0)) + 302), (camera_get_view_y(view_get_camera(0)) + 120))
draw_sprite(spr_day_night_icon, modo_noche, (camera_get_view_x(view_get_camera(0)) + 330), (camera_get_view_y(view_get_camera(0)) + 130))
draw_sprite(spr_date_time_bg, 0, (camera_get_view_x(view_get_camera(0)) + 44), (camera_get_view_y(view_get_camera(0)) + 152))
draw_set_font(global.numbers_datetime)
draw_set_color(c_white)
draw_text((camera_get_view_x(view_get_camera(0)) + 47), (camera_get_view_y(view_get_camera(0)) + 156), string_hash_to_newline(fecha))
draw_text((camera_get_view_x(view_get_camera(0)) + 152), (camera_get_view_y(view_get_camera(0)) + 156), string_hash_to_newline(hora))

